---
title: "Server Maintenance"
author: ""
date: "`r doc_date()`"
output:
  BiocStyle::html_document:
      toc: yes
      toc_depth: 3
      toc_float: yes
      code_folding: "hide" 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here are some basic instructions and advice for maintaining the servers:

# Adding a new account

1.  Add the user: `sudo add user USERID`
2.  Type in your password
3.  Create a password for the new user
4.  Check that this successfully created a user directory `cd /home/USERID`
5.  On mti-01
    1.  Create data folder: `cd /mnt/raid0_data/` or `/mnt/raid5_data` then `mkdir USERID`

    2.  Make user the owner of data folder `sudo chown USERID`
6.  On mti-02
    1.  Create data folder `cd /data/`then `sudo mkdir USERID`

    2.  Make user the owner of data folder `sudo chown USERID`

# Check memory usage 
You can check the capacity left in /home and /data by running `df -h`   
/dev/sdb2 corresponds to  /home    
/deve/sda1 corresponds to /data


You can check how much individual users are taking up in either with 

`sudo du -hs /home/* ` and `sudo du -hs /data/*`

Make sure no one is using more than 50Gb in home

# Restarting the server
The server is scheduled to be rebooted on: 

Wed 5th July 2023 - Midnight    
Sunday 15th January 2024 - Midnight    
Wednesday 10th July 2024 - Midnight    

You will need to schedule more, every 6 months and give eveyrone 24 hour notice. 

# Checking processing and Killing jobs

Check what jobs are taking up the most resources with: `top` 

If a job is taking up too many resources, or too much time, you can kill it as follows: `kill` followed by the PID 


# Installing new software

You can install new software with `pip install` and `conda install`. If you want to installation to be system wide, and not just for yourself, you can `sudo` first. 


# Updating software and keeping security up to date
Once a year you shoudl go to Ivan in IT and get him to  run `sudo apd update` to update software and keep security up to date


# Setting up jupiter notebooks for users

You can find a tutorial for setting up a Jupyter notebook [here](https://www.dropbox.com/s/nh21x2f2bzcw9ya/Jupyter%20Notebook%20on%20the%20server-20230119_120326-Meeting%20Recording.mp4?dl=0). 
