---
title: "CRISPR screen how to "
author: "Holly A. R. Giles"
date: "`r doc_date()`"
output:
  BiocStyle::html_document:
      toc: yes
      toc_depth: 3
      toc_float: yes
      code_folding: "hide" 
---

------------------------------------------------------------------------

This vignette explains the steps to go through from raw fastq files downloaded from the core facility, through to analysis of CRISPR screening data. It also demonstrates different packages for downstream analysis.

If you have not run on a server before

1.  Download anaconda
    1.  Here is a good tutorial: <https://linuxhint.com/conda-command-not-found/>
2.  Set up the following conda environment:

<!-- -->

    conda create -n [a-env-name you want e.g. mageck-vispr]  python=3.7
    conda activate mageck-vispr
    conda install -c conda-forge mamba
    conda install -c bioconda -c conda-forge mageck
    mamba install -c bioconda -c conda-forge mageck-vispr

You should then have the mageck-vispr environment ready to run, later on you can just call mageck-vispr.

To run the pipeline:

1.  Get all the data in place to run pipeline
    1.  Put fastqs into a directory, direct from the FTP download

    2.  Get a library file. When starting from fastq files, MAGeCK needs to know the sgRNA sequence and its targeting gene. Such information is provided in the sgRNA library file, and can be specified by the *-l/\--list-seq* option in **run** or **count** subcommand. e.g. from here: <https://github.com/dbarrell/pipeline_external/blob/main/libraries/yusa1_singleGene.csv> or here: <https://sourceforge.net/p/mageck/wiki/libraries/>
2.  Activate the snakemake pipeline

To interpret the output
